#!/usr/bin/python3
"""
Contains the BaseModel class
"""
import uuid
from datetime import datetime

class BaseModel:
    """
    BaseModel class
    """
    def __init__(self):
        """
        Initializes a BaseModel instance

        Sets the following instance attributes:
        id (str): unique id generated by uuid
        created_at (datetime): datetime object of creation time
        updated_at (datetime): datetime object of last modification time
        """
        self.id = str(uuid.uuid4())
        self.created_at = datetime.now()
        self.updated_at = datetime.now()

    def __str__(self):
        """
        Returns a string representation of the BaseModel instance,
        including the class name, id, created_at, and updated_at.
        """
        return f"[{self.__class__.__name__}] ({self.id}) {self.__dict__}"

    def save(self):

        """
        Updates the public instance attribute updated_at with the current
        datetime.
        """
        self.updated_at = datetime.now()

    def to_dict(self):
        """
        Returns a dictionary representation of the BaseModel instance,
        including the class name, id, created_at, and updated_at.
        """
        obj_dict = self.__dict__.copy()
        obj_dict["__class__"] = self.__class__.__name__
        obj_dict["created_at"] = self.created_at.isoformat()
        obj_dict["updated_at"] = self.updated_at.isoformat()

        return obj_dict